### ISSUE TITLE
Have you been able to run this on Linux VM?

### ISSUE THREAD

**Issue by zenbane** [pharrisee/TheFrontLinuxServerInfo#1]
Is this for a baremetal install? Tried on Windows VM - no dice. Followed your directions (big thank you!) to a T but am unable to get past join server prompt (ubuntu VM). See server in list, Start button greyed out. Tried opening all ports to my IP address (this is hosted on a VPS), still no luck.

**Comment by pharrisee** [comment]
If you are running this in a natted network (i.e. at home) then you need to add an extra bit to the start script, change your equivalent of this line:
`ProjectWar_Start?DedicatedServer?MaxPlayers=8?`
to be
`ProjectWar_Start?DedicatedServer?MaxPlayers=8?udrs=steam`
