### ISSUE TITLE
NPC Movement

### ISSUE THREAD

**Issue by PaRaLyZe** [pharrisee/TheFrontLinuxServerInfo#2]
After following your guide, the server runs ( ! Thanx ! )

However i have found that there is no NPC movement, and they will stay in place

( Centos 7 ) & ( Ubuntu )

**Comment by pharrisee** [comment]
I had the exact same issue and struggled to fix it, I can't even tell you how I fixed, even less can I tell you what was wrong.  This only happened after upgrading to 1.0.9.  Good luck

**Comment by Spidees** [comment]
I made now fresh intall and I have same issue.
